<?php

/*
@file islandora_lab_object_lcms.module

Module for LCMS

*/


/**
 * * Implements hook_islandora_required_objects()
 * */
function islandoralab_objectlcms_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_lab_object_lcms');
  $lcms_cm = $connection->repository->constructObject('islandora:lcms_cmodel');
  $lcms_cm->owner = 'fedoraAdmin';
  $lcms_cm->label = 'Bioinformatics LCMS Content Model';
  $lcms_cm->models = 'fedora-system:ContentModel-3.0';

  // RELS
  $lcms_cm->relationships->add(FEDORA_MODEL_URI, 'hasModel', 'islandora:lab_object_cmodel');
  $lcms_cm->relationships->add("", 'datarelSpecimen', 'islandora:specimen_cmodel');

  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $lcms_cm->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/lcms_ds_composite_model.xml", FALSE);
  $lcms_cm->ingestDatastream($datastream);
  
  //Create relationship with LabObject
  $lcms_cm->relationships->add(FEDORA_MODEL_URI, 'hasModel', 'islandora:lab_object_cmodel');
  $lcms_cm->relationships->add("", 'datarel_specimen', 'islandora:specimen_cmodel');

  $lcms_collection = $connection->repository->constructObject('islandora:lcms_collection');
  $lcms_collection->owner = 'fedoraAdmin';
  $lcms_collection->label = 'LCMS Collection';
  $lcms_collection->models = 'islandora:collectionCModel';
  $lcms_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  $datastream = $lcms_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/lcms_collection_policy.xml", FALSE);
  $lcms_collection->ingestDatastream($datastream);



  return array(
    'islandora_lab_object_lcms' => array(
      'title' => 'Bioinformatics LCMS',
      'objects' => array(
          $lcms_cm,
      ),
    ),
  );
}


function islandoralab_objectlcms_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_lab_object_lcms');
  return array(
    'LCMS Form' => array(
      'form_file' => "$module_path/xml/islandoralab_objectlcms_form.xml",
    ),
  );
}


function islandoralab_objectlcms_islandora_xml_form_builder_form_associations() {
  $module_path = drupal_get_path('module', 'islandora_lab_object_lcms');
  return array(
    'islandoralab_objectlcms_form' => array(
      'content_model' => 'islandora:lcms_cm',
      'form_name' => 'LCMS Form',
      'dsid' => 'LCMS',
      'title_field' => array('run_title'),
      'transform' => '',
      //'self_transform' => "$module_path/xml/islandoralab_objectlcms_transform.xsl",
      'template' => FALSE,
    ),
  );
}

function islandoralab_objectlcms_islandora_lcms_cm_islandora_ingest_steps(array $configuration) {
  return array(
    'islandoralab_objectlcms_csv_file_upload' => array(
      'weight' => 8,
      'type' => 'form',
      'form_id' => 'islandoralab_objectlcms_upload_csv_form',
      'module' => 'islandora_lab_object_lcms',
      'file' => 'includes/islandoralab_objectlcms_upload_csv.form.inc'
    ),
    'islandoralab_objectlcms_raw_file_upload' => array(
      'weight' => 9,
      'type' => 'form',
      'form_id' => 'islandoralab_objectlcms_upload_raw_form',
      'module' => 'islandora_lab_object_lcms',
      'file' => 'includes/islandoralab_objectlcms_upload_raw.form.inc'
    )
  );
}

function islandoralab_objectlcms_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_lab_object_lcms' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/lcms_theme',
      'pattern' => 'islandoralab_objectlcms__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

function islandoralab_objectlcms_islandora_lcms_cm_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_lab_object_lcms', array('islandora_object' => $object));
  return array('' => $output);
}



