<?php

/*
@file

Module for LCMS

*/


/**
 * * Implements hook_islandora_required_objects()
 * */
function islandora_bioinformatics_lcms_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics_lcms');
  $lcms_cm = $connection->repository->constructObject('islandora:lcms_cm');
  $lcms_cm->owner = 'fedoraAdmin';
  $lcms_cm->label = 'Bioinformatics LCMS Content Model';
  $lcms_cm->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $lcms_cm->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/lcms_ds_composite_model.xml", FALSE);
  $lcms_cm->ingestDatastream($datastream);
  return array(
    'islandora_bioinformatics_lcms' => array(
      'title' => 'Bioinformatics LCMS',
      'objects' => array(
          $lcms_cm,
      ),
    ),
  );
}


function islandora_bioinformatics_lcms_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics_lcms');
  return array(
    'LCMS Form' => array(
      'form_file' => "$module_path/xml/islandora_bioinformatics_lcms_form.xml",
    ),
  );
}


function islandora_bioinformatics_lcms_islandora_xml_form_builder_form_associations() {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics_lcms');
  return array(
    'islandora_bioinformatics_lcms_form' => array(
      'content_model' => 'islandora:lcms_cm',
      'form_name' => 'LCMS Form',
      'dsid' => 'LCMS',
      'title_field' => array('run_title'),
      'transform' => '',
      //'self_transform' => "$module_path/xml/islandora_bioinformatics_lcms_transform.xsl",
      'template' => FALSE,
    ),
  );
}

function islandora_bioinformatics_lcms_islandora_lcms_cm_islandora_ingest_steps(array $configuration) {
  return array(
    'islandora_bioinformatics_lcms_csv_file_upload' => array(
      'weight' => 8,
      'type' => 'form',
      'form_id' => 'islandora_bioinformatics_lcms_upload_csv_form',
      'module' => 'islandora_bioinformatics_lcms',
      'file' => 'includes/islandora_bioinformatics_lcms_upload_csv.form.inc'
    ),
    'islandora_bioinformatics_lcms_raw_file_upload' => array(
      'weight' => 9,
      'type' => 'form',
      'form_id' => 'islandora_bioinformatics_lcms_upload_raw_form',
      'module' => 'islandora_bioinformatics_lcms',
      'file' => 'includes/islandora_bioinformatics_lcms_upload_raw.form.inc'
    )
  );
}

function islandora_bioinformatics_lcms_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_bioinformatics_lcms' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/lcms_theme',
      'pattern' => 'islandora_bioinformatics_lcms__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

function islandora_bioinformatics_lcms_islandora_lcms_cm_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_bioinformatics_specimen', array('islandora_object' => $object));
  return array('' => $output);
}



