<?php

/*
@file

Module for LCMS

*/

function islandora_lab_object_lcms_menu(){
  return array(
    'islandora/object/%islandora_object/test_ingest_lcms' => array(
        'title' => 'Ingest LCMS',
        'page callback' => 'islandora_bioinformatics_lcms_lab_object_lcms_ingest',
        'page arguments' => array(2),
        'access callback' => TRUE,
      )
  );
}


function islandora_lab_object_lcms_forms($form_id, $args){
  /**
   * @author Nolan Phillips ncphillips@upei.ca
   *
   * @param $form_id
   * @param $args
   * @return $forms
   *
   * Implements hook_forms($form_id, $args)
   *
   * This function is used to associate a new Form ID with an existing form constructor.
   */
  $forms = array();
  switch($form_id){
    /**
     * ## Related LCMS Form
     * __Form ID:__ `related_lcms_form`
     *
     * __Form Base ID:__ `related_islandora_objects_form`
     *
     * Creates a `related_islandora_objects_form` with the `$cmodel` and `$relationships`
     * arguments set as:
     *
     *      $cmodels = array('islandora:lcms_cmodel');
     *      $relationships = array(FEDORA_RELS_EXT_URI => array('isPartOf'),);
     */
    case 'related_lcms_form':
      $cmodels = array('islandora:lcms_cmodel');
      $relationships = array(FEDORA_RELS_EXT_URI => array('isPartOf', 'isMemberOf',),);

      $args[] = $cmodels;
      $args[] = $relationships;

      $forms['related_lcms_form'] = array(
        'callback' => 'related_islandora_objects_form',
        'callback arguments' => $args,
      );
      break;
  }
  return $forms;
}

/**
 * * Implements hook_islandora_required_objects()
 * */
function islandora_lab_object_lcms_islandora_required_objects(IslandoraTuque $connection) {
  module_load_include('inc', 'islandora_bioinformatics_base', 'base_functions');

  $module_path = drupal_get_path('module', 'islandora_lab_object_lcms');
  $lcms_cm = $connection->repository->constructObject('islandora:lcms_cmodel');
  $lcms_cm->owner = 'fedoraAdmin';
  $lcms_cm->label = 'Bioinformatics LCMS Content Model';
  $lcms_cm->models = 'fedora-system:ContentModel-3.0';

  // RELS
  $lcms_cm->relationships->add(FEDORA_MODEL_URI, 'hasModel', 'islandora:lab_object_cmodel');

  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $lcms_cm->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/lcms_ds_composite_model.xml", FALSE);
  $lcms_cm->ingestDatastream($datastream);
  
  //Create relationship with LabObject
  $lcms_cm->relationships->add(FEDORA_MODEL_URI, 'hasModel', 'islandora:lab_object_cmodel');

  $lcms_collection = $connection->repository->constructObject('islandora:lcms_collection');
  $lcms_collection->owner = 'fedoraAdmin';
  $lcms_collection->label = 'LCMS Collection';
  $lcms_collection->models = 'islandora:collectionCModel';
  $lcms_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  $datastream = $lcms_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/lcms_collection_policy.xml", FALSE);
  $lcms_collection->ingestDatastream($datastream);

  // relationships between lcms and specimen/assay
  $specimen_cm = islandora_object_load("islandora:specimen_cmodel");
  $assay_cm = islandora_object_load("islandora:assay_cmodel");

  add_hasPart($specimen_cm, "islandora:lcms_cmodel");
  add_hasPart($assay_cm, "islandora:lcms_cmodel");

  add_isPartOf($lcms_cm, "islandora:specimen_cmodel");
  add_isPartOf($lcms_cm, "islandora:assay_cmodel");

  return array(
    'islandora_lab_object_lcms' => array(
      'title' => 'Bioinformatics LCMS',
      'objects' => array(
          $lcms_cm,
      ),
    ),
  );
}


function islandora_lab_object_lcms_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_lab_object_lcms');
  return array(
    'LCMS Form' => array(
      'form_file' => "$module_path/xml/islandora_lab_object_lcms_form.xml",
    ),
  );
}


function islandora_lab_object_lcms_islandora_xml_form_builder_form_associations() {
  $module_path = drupal_get_path('module', 'islandora_lab_object_lcms');
  return array(
    'islandora_lab_object_lcms_form' => array(
      'content_model' => 'islandora:lcms_cm',
      'form_name' => 'LCMS Form',
      'dsid' => 'LCMS',
      'title_field' => array('run_title'),
      'transform' => '',
      //'self_transform' => "$module_path/xml/islandora_lab_object_lcms_transform.xsl",
      'template' => FALSE,
    ),
  );
}

function islandora_lab_object_lcms_islandora_lcms_cm_islandora_ingest_steps(array $configuration) {
  return array(
    'islandora_lab_object_lcms_csv_file_upload' => array(
      'weight' => 8,
      'type' => 'form',
      'form_id' => 'islandora_lab_object_lcms_upload_csv_form',
      'module' => 'islandora_lab_object_lcms',
      'file' => 'includes/islandora_lab_object_lcms_upload_csv.form.inc'
    ),
    'islandora_lab_object_lcms_raw_file_upload' => array(
      'weight' => 9,
      'type' => 'form',
      'form_id' => 'islandora_lab_object_lcms_upload_raw_form',
      'module' => 'islandora_lab_object_lcms',
      'file' => 'includes/islandora_lab_object_lcms_upload_raw.form.inc'
    )
  );
}

function islandora_lab_object_lcms_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_lab_object_lcms' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/lcms_theme',
      'pattern' => 'islandora_lab_object_lcms__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

function islandora_lab_object_lcms_islandora_lcms_cm_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_lab_object_lcms', array('islandora_object' => $object));
  return array('' => $output);
}


/**
 * @author Quintin Dawson qdawson@upei.ca
 * This function should create a new lcms object and create a relationship between it and the $parent object
 */

function islandora_bioinformatics_lcms_lab_object_lcms_ingest(AbstractObject $parent) {
  $collection = islandora_object_load('islandora:lcms_collection');
  if (($configuration = islandora_bioinformatics_lcms_lab_object_load_ingest_configuration($collection)) !== FALSE) {
    module_load_include('inc', 'islandora', 'includes/ingest.form');
    return drupal_get_form('islandora_ingest_form', $configuration);
  }
  drupal_not_found();
}


function islandora_bioinformatics_lcms_lab_object_load_ingest_configuration(AbstractObject $collection) {
  $is_collection_object = in_array('islandora:collectionCModel', $collection->models);
  $has_policy = isset($collection['COLLECTION_POLICY']);
  if (!$is_collection_object || !$has_policy) {
    return array();
  }

  $object = $collection->repository->constructObject('islandora');
  $object->label = 'New Object';

  $results = $object->relationships->get(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', $collection->id);
  if (empty($results)) {
    $object->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', $collection->id);
  }

  $policy = new CollectionPolicy($collection['COLLECTION_POLICY']->content);

  return array(
    'collection' => $collection,
    'models' => array_keys($policy->getContentModels()),
    'objects' => array($object),
    'parent' => $collection->id,
  );
}



