<?php
/**
 * * Implements hook_islandora_required_objects()
 * */
function islandora_bioinformatics_lcms_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics_lcms');
  $lcms_cm = $connection->repository->constructObject('islandora:lcms_cm');
  $lcms_cm->owner = 'fedoraAdmin';
  $lcms_cm->label = 'Bioinformatics LCMS Content Model';
  $lcms_cm->models = 'fedora-system:ContentModel-3.0';

  // RELS
  $lcms_cm->relationships->add(FEDORA_MODEL_URI, 'hasModel', 'islandora:lab_object_cmodel');
  $lcms_cm->relationships->add("", 'datarelSpecimen', 'islandora:specimen_cmodel');

  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $lcms_cm->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/lcms_ds_composite_model.xml", FALSE);
  $lcms_cm->ingestDatastream($datastream);
  return array(
    'islandora_bioinformatics_lcms' => array(
      'title' => 'Bioinformatics LCMS',
      'objects' => array(
          $lcms_cm,
      ),
    ),
  );
}

function islandora_bioinformatics_lcms_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics_lcms');
  return array(
    'LCMS Form' => array(
      'form_file' => "$module_path/xml/islandora_bioinformatics_lcms_form.xml",
    ),
  );
}

function islandora_bioinformatics_lcms_islandora_xml_form_builder_form_associations() {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics_lcms');
  return array(
    'islandora_bioinformatics_lcms_form' => array(
      'lcms_cm' => 'islandora:lcms',
      'form_name' => 'LCMS Form',
      'dsid' => 'LCMS',
      'title_field' => array('taxonomy', 'species'),
      'transform' => '',
      //'self_transform' => "$module_path/xml/islandora_bioinformatics_lcms_transform.xsl",
      'template' => FALSE,
    ),
  );
}

